server:
  port: 8090
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848