server:
  port: 8081
  servlet:
    context-path: /api
spring:
    profiles:
        active: dev
    mvc:
      path match:
        matching-strategy: ANT_PATH_MATCHER
api:
  client:
    access-key:
    secret-key: